version: '3'
services:
  postgresql:
    image: bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=root
      - POSTGRESQL_DATABASE=root      
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data