name: Docker

on:
  workflow_call:
    

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configuração inicial do Docker
      uses: docker/setup-buildx-action@v2.9.1

    - name: Baixando o artefato do repositório
      uses: actions/download-artifact@v2.1.1
      with:
        name: Aplicação Go

    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        username: t0malexander
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Construindo a imagem Docker
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: t0malexander/go-cicd:${{ github.ref_name }}
