name: Entrega Contínua (CD)

on:
  workflow_call:

jobs:

  EC2:
    runs-on: ubuntu-latest
    steps:
    
    - name: Baixando o artefato do repositório
      uses: actions/download-artifact@v2.1.1
      with:
        name: Aplicação Go
    - uses: actions/checkout@v3

    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: /home/${{ secrets.REMOTE_USER }}
        EXCLUDE: "/data"

    - name: remote ssh command
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          export HOST=${{ secrets.DB_HOST }}
          expor USER=${{ secrets.DB_USER }}
          export PASSWORD=${{ secrets.DB_PASSWORD }}
          export DB_NAME=${{ secrets.DB_NAME }}
          export PORT=${{ secrets.DB_PORT }}
