# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "gh-actions" ]
  pull_request:
    branches: [ "gh-actions" ]

jobs:
  testes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configuração inicial do Golang
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Compilando a imagem Docker
      run: docker-compose build

    - name: Subindo o banco de dados
      run: docker-compose up -d

    - name: Teste do banco de dados
      run: go test -v main_test.go

  build:
    needs: testes
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Compilando a aplicação Go
      run: go build -v main.go